version: '3.0'

services:
  main: # само приложение
    container_name: main
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on: # зависит от бд
      - postgres
    restart: always
  postgres: # база данных
    container_name: postgres
    image: postgres:12
    env_file:
      - .dev.env
    environment: # в документации так указано
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes: # чтобы не терять данные внутри бд
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
